// Export the dice the web app draws as editable source files.
//
//   npm run models
//
// Reads the same geometry as the 3D roller (apps/web/src/dice3d/diceModels.ts:
// bevelled d4, d6, d8, d10, d12, d20 with the numbering rules of real dice) and
// writes, per die, into packages/dice-models/:
//
//   openscad/generated/dN.scad   parametric, numbers engraved; edit and render
//   exports/obj/dN.obj           for Blender or any 3D editor
//   exports/stl/dN.stl           ready to slice, numbers engraved (rendered by
//                                OpenSCAD from the .scad; skipped without it)
//   exports/faces/dN.json        which number is on which face, and where
//
// Units are millimetres. Node 22.18+ runs the TypeScript source directly.
// OpenSCAD is found on PATH, or set OPENSCAD to its executable.
import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { Vector3 } from "three";
import { createDiceModel, MODEL_SIDES } from "../apps/web/src/dice3d/diceModels.ts";

const root = resolve(fileURLToPath(new URL("..", import.meta.url)));
const out = join(root, "packages", "dice-models");
const MM = 9.5;                    // model units to millimetres: d20 about 20 mm, d6 about 16 mm
const r = (n) => Math.round(n * 10000) / 10000;

for (const dir of ["openscad/generated", "exports/obj", "exports/stl", "exports/faces"]) {
  mkdirSync(join(out, dir), { recursive: true });
}

function mesh(model) {
  const pos = model.geometry.getAttribute("position");
  const points = [], index = new Map(), triangles = [];
  for (let i = 0; i < pos.count; i += 3) {
    const tri = [0, 1, 2].map((k) => {
      const v = new Vector3().fromBufferAttribute(pos, i + k).multiplyScalar(MM);
      const key = [r(v.x), r(v.y), r(v.z)].join(",");
      if (!index.has(key)) { index.set(key, points.length); points.push([r(v.x), r(v.y), r(v.z)]); }
      return index.get(key);
    });
    if (tri[0] !== tri[1] && tri[1] !== tri[2] && tri[0] !== tri[2]) triangles.push(tri);   // counter-clockwise from outside
  }
  return { points, triangles };
}

// Where each number goes: a frame on the face (right, up, outward normal) and
// a size that fits inside it. A d4 is read at the top point, so each face
// carries the three corner numbers instead of one face number.
function labels(model) {
  if (model.sides === 4) {
    return model.faces.flatMap((face) => face.vertices.map((corner) => {
      const value = model.vertices.findIndex((v) => v.distanceTo(corner) < 1e-4) + 1;
      const up = corner.clone().sub(face.center).normalize();
      return { value, at: face.center.clone().lerp(corner, 0.5), normal: face.normal, up, size: face.radius * 0.7 };
    }));
  }
  return model.faces.map((face) => ({ value: face.value, at: face.center, normal: face.normal, up: face.up,
    size: face.radius * (face.value >= 10 ? 0.95 : 1.15) }));
}

function frame(l) {
  const right = l.up.clone().cross(l.normal).normalize();
  const t = l.at.clone().multiplyScalar(MM);
  return [[right.x, l.up.x, l.normal.x, t.x], [right.y, l.up.y, l.normal.y, t.y],
    [right.z, l.up.z, l.normal.z, t.z], [0, 0, 0, 1]].map((row) => row.map(r));
}

function scad(model, m, ls) {
  const name = `d${model.sides}`;
  const sixNine = model.sides >= 8;
  return `// Open Dice ${name}, generated by scripts/export-models.mjs from the same
// geometry the web roller draws. By Zein Alaouie, CC BY 4.0: credit
// "Dice model by Zein Alaouie (Open Dice), CC BY 4.0" when you share this
// model, a remix or prints. https://github.com/Greycell-open/OpenDice
// Edit the parameters, then
// Render (F6) and Export as STL. Regenerate with: npm run models
//
// Opposite faces sum to ${model.sides === 4 ? "n/a (a d4 is read at its top point)" : model.sides + 1}.

size_scale     = 1.0;    // 1.0 = standard size (d20 about 20 mm, d6 about 16 mm); 1.25 is 25 percent larger
engrave_depth  = 0.6;    // mm into each face
font           = "Liberation Sans:style=Bold";
text_scale     = 1.0;    // grow or shrink every number
mark_six_nine  = ${sixNine};  // a dot after 6 and 9 so they can be told apart

points = ${JSON.stringify(m.points)};
// Counter-clockwise from outside in the source; OpenSCAD wants clockwise.
faces = ${JSON.stringify(m.triangles.map((t) => [t[0], t[2], t[1]]))};

// [number, text height in mm, placement on the face]
labels = [
${ls.map((l) => `  [${l.value}, ${r(l.size * MM)}, ${JSON.stringify(frame(l))}]`).join(",\n")}
];

function label_text(n) = (mark_six_nine && (n == 6 || n == 9)) ? str(n, ".") : str(n);

scale(size_scale) difference() {
  polyhedron(points = points, faces = faces, convexity = 2);
  for (l = labels)
    multmatrix(l[2])
      translate([0, 0, -engrave_depth / size_scale])
        linear_extrude(engrave_depth / size_scale + 0.05)
          text(label_text(l[0]), size = l[1] * 0.62 * text_scale, font = font,
               halign = "center", valign = "center");
}
`;
}

function obj(model, m) {
  return `# Open Dice d${model.sides}, from scripts/export-models.mjs. Millimetres.\n` +
    `# By Zein Alaouie, CC BY 4.0. Credit: "Dice model by Zein Alaouie (Open Dice), CC BY 4.0"\n` +
    `# Face numbers: see ../faces/d${model.sides}.json\no d${model.sides}\n` +
    m.points.map((p) => `v ${p.join(" ")}`).join("\n") + "\n" +
    m.triangles.map((t) => `f ${t.map((i) => i + 1).join(" ")}`).join("\n") + "\n";
}

function faces(model, ls) {
  return JSON.stringify({
    die: `d${model.sides}`, units: "mm",
    author: "Zein Alaouie", license: "CC-BY-4.0", credit: "Dice model by Zein Alaouie (Open Dice), CC BY 4.0", read: model.sides === 4 ? "top point" : "upper face",
    opposite_faces_sum: model.sides === 4 ? null : model.sides + 1,
    labels: ls.map((l) => ({ value: l.value, center: l.at.toArray().map((n) => r(n * MM)),
      normal: l.normal.toArray().map(r), up: l.up.toArray().map(r), text_height: r(l.size * MM * 0.62) })),
  }, null, 1) + "\n";
}

for (const sides of MODEL_SIDES) {
  const model = createDiceModel(sides);
  const m = mesh(model);
  const ls = labels(model);
  const name = `d${sides}`;
  writeFileSync(join(out, "openscad", "generated", `${name}.scad`), scad(model, m, ls));
  writeFileSync(join(out, "exports", "obj", `${name}.obj`), obj(model, m));
  writeFileSync(join(out, "exports", "faces", `${name}.json`), faces(model, ls));
  console.log(`${name}: ${m.points.length} points, ${m.triangles.length} triangles, ${ls.length} numbers`);
}

const openscad = process.env.OPENSCAD || "openscad";
for (const sides of MODEL_SIDES) {
  const name = `d${sides}`;
  try {
    execFileSync(openscad, ["-o", join(out, "exports", "stl", `${name}.stl`),
      join(out, "openscad", "generated", `${name}.scad`)], { stdio: "ignore" });
    console.log(`${name}.stl rendered with numbers engraved`);
  } catch {
    console.log("OpenSCAD not found: STL files left as they were (set OPENSCAD to its executable)");
    break;
  }
}
